services:
  db:
    image: postgres:16
    container_name: studyops-db
    environment:
      POSTGRES_DB: studyops
      POSTGRES_USER: studyops
      POSTGRES_PASSWORD: studyops
    ports:
      - "5433:5432"
    volumes:
      - studyops_pgdata:/var/lib/postgresql/data

volumes:
  studyops_pgdata:
